# This workflow covers basic actions for deploying AWS CDK apps
# The workflow relies on shell scripts at the root of the CDK directory
# These shell scripts do most of the work, making this script more interchangeable
# This will: install dependencies, build, synth, perform security audit, and test deploy

name: AWS CDK Github Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
        - uses: actions/checkout@v3
        - name: Set up Python 3.9
            uses: actions/setup-python@v4
            with:
            python-version: "3.9"
        - name: Set up Node
            uses: actions/setup-node@v3
            with:
            node-version: "18"
        - name: Install Node and Python dependencies and CDK
            run: |
                python -m pip install --upgrade pip
                npm install -g aws-cdk
                sh test-dependencies.sh
        - name: Install CDK app dependencies
            run:
                npm ci
        - name: Lint CDK app code
            run:
                sh test-lint.sh
        - name: Build CDK app
                sh test-build.sh
        - name: Synthesize CDK app
                sh test-synth.sh
        - name: Deploy CDK app
                sh test-deploy.sh
        - name: Security audit of CDK app
                sh test-security.sh
        - name: Perform end to end test of CDK app
                sh test-e2e.sh
        - name: Perform multi-region test deployment
                sh test-regional.sh